# config for training

trainer:
  checkpoint: "./tune/2spk_pit_psm_k"
  optimizer: "adam"
  lr: 1.0e-3
  momentum: 0.9
  weight_decay: 1.0e-5
  clip_norm: 200
  min_lr: 1.0e-10
  patience: 0
  factor: 0.7
  disturb_std: 0

model:
  num_spks: 1
  rnn: "lstm"
  num_layers: 1
  hidden_size: 512
  dropout: 0.5
  non_linear: "relu"
  bidirectional: true

spectrogram_reader:
  frame_shift: 256
  frame_length: 512
  window: "hann"
  transpose: true
  # false => produce psm
  # true  => produce irm
  apply_abs: false

train_scp_conf:
  mixture: "./data/2spk/train/mix.scp"
  spk1: "./data/2spk/train/spk1.scp"
  uttAdapt: "./data/2spk/train/uttAdapt.scp"

valid_scp_conf:
  mixture: "./data/2spk/dev/mix.scp"
  spk1: "./data/2spk/dev/spk1.scp"
  uttAdapt: "./data/2spk/dev/uttAdapt.scp"

debug_scp_conf:
  mixture: "./data/2spk/debug/mix.scp"
  spk1: "./data/2spk/debug/spk1.scp"
  uttAdapt: "./data/2spk/debug/uttAdapt.scp"

dataloader:
  shuffle: true
  batch_size: 8
  drop_last: false
  apply_log: false
  mvn_dict: 

